# Generated by Django 4.2.6 on 2023-10-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_projects_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='verification_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='github_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='projects',
            name='website_link',
            field=models.CharField(max_length=100),
        ),
    ]
