# Generated by Django 4.2.6 on 2023-11-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_certification_verification_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='icon',
            field=models.TextField(default=None),
        ),
    ]
