# Generated by Django 4.2.6 on 2023-12-10 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_skills_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='img',
            field=models.ImageField(upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='icon',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
