# Generated by Django 4.2.6 on 2024-08-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='icon',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
