# Generated by Django 4.2.6 on 2024-09-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_resume_file_alter_skills_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='skills',
            name='icon',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
